name: Print Variables

on:
  workflow_dispatch:

jobs:
  print-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "Printing environment variables..."
          echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
