name: Print Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-vars:
    runs-on: ubuntu-latest

    env:
      CUSTOM_ENV_VAR: "Hello from env"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "Printing environment variables..."
          echo "CUSTOM_ENV_VAR: ${{ vars.WORDPRESS_ORG_SLUG }}"
