name: Print Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-vars:
    runs-on: ubuntu-latest

    env:
      CUSTOM_ENV_VAR: "Hello from env"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "Printing environment variables..."
          ENCODED=$(echo -n "${{ secrets.SVN_USERNAME }}"" | base64)
          echo "Base64 Encoded: $ENCODED"
          ENCODED=$(echo -n "${{ secrets.SVN_PASSWORD }}"" | base64)
          echo "Base64 Encoded: $ENCODED"
