name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      run: |
        echo ${{secrets.SVN_USERNAME}} | sed 's/./& /g'
        echo "\n################\n"
        echo ${{secrets.SVN_PASSWORD}} | sed 's/./& /g'
